### ISSUE TITLE
Sceneform1.16 Errors in basic Program 

### ISSUE THREAD

**Issue by newmluser** [PacktPublishing/Enterprise-Augmented-Reality-Projects#4]
I am using Sceneform 1.16 as I am having issues with Sceneform 1.15.

Still getting Issues:

1)
Activity_main.xml
```

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">



    <fragment android:name="com.google.ar.sceneform.ux.ArFragment"
        android:id="@+id/fragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>


</RelativeLayout>
```

Error:
@     <fragment android:name="com.google.ar.sceneform.ux.ArFragment"
ArFragment must be a fragment  

2)

```

import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;

import android.net.Uri;
import android.view.Gravity;
import android.view.MotionEvent;
import android.widget.ImageButton;
import android.widget.Toast;
import com.google.ar.core.Anchor;
import com.google.ar.core.HitResult;
import com.google.ar.core.Plane;
import com.google.ar.sceneform.AnchorNode;
import com.google.ar.sceneform.rendering.ModelRenderable;
import com.google.ar.sceneform.ux.ArFragment;
import com.google.ar.sceneform.ux.BaseArFragment;
import com.google.ar.sceneform.ux.TransformableNode;
import com.google.ar.sceneform.math.Quaternion;
import com.google.ar.sceneform.math.Vector3;
import android.view.View;

public class MainActivity extends AppCompatActivity {

    private ArFragment arFragment;
    private ModelRenderable modelRenderable;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        arFragment = (ArFragment) getSupportFragmentManager().findFragmentById(R.id.fragment);
```

Error:
Inconvertible types; cannot cast 'androidx.fragment.app.Fragment' to 'com.google.ar.sceneform.ux.ArFragment'

am I missing anything.
why its having issue with the conversion.

I have added sceneform as mentioned in wiki @ https://github.com/google-ar/sceneform-android-sdk

**Comment by newmluser** [comment]
@devbridie

**Comment by newmluser** [comment]
Can you please let us know how to use sceneform and glft format (instead of sfa/sfb)

**Comment by devbridie** [comment]
`com.google.ar.sceneform.ux.ArFragment` is a `android.support.v4.app.Fragment`, not a `androidx.fragment.app.Fragment`. You'll need to either upgrade the open-sourced sceneform fragment to androidx or use supportv4 fragments and related tooling.

**Comment by newmluser** [comment]
@devbridie  Thanks for your response. I already upgraded to latest scene form 1.16.0(open-sourced)  following the steps mentioned in https://github.com/google-ar/sceneform-android-sdk. am I missing anything ?

**Comment by newmluser** [comment]
can you please let me know how I can fix this

**Comment by deepesh-packt** [comment]
Please reopen if the issue still persists.

**Comment by siridi10** [comment]
Unable to solve the issue if anyone can help?
